WITH RECURSIVE A AS(
SELECT 0 AS num
union ALL
SELECT num+1 FROM A WHERE num<23
)


SELECT hr.num, COUNT(B.DATETIME)
FROM ANIMAL_OUTS AS B
RIGHT JOIN A AS hr
ON hr.num = HOUR(B.DATETIME)
GROUP BY hr.num